from app.models.port import Port
from app.models.scan import Scan
from app.models.user import User
from app.models.protocol import Protocol
from app.models.scanType import ScanType
from app.models.equipment import Equipment
from app.models.equipmentPort import EquipmentPort
from app.models.scanEquipment import ScanEquipment
from app.models.vulnerabilities import Vulnerabilities
from app.models.vulnerabilityType import VulnerabilityType
